engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
exclude_paths:
  - "Gulpfile.js"
  - "test/"
  - "build_scripts/"
