language: node_js
dist: trusty
node_js:
  - node
env:
  - TEST_SUITE=unit-test
  - TEST_SUITE=e2e-test
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script: "gulp $TEST_SUITE"
